name: AreaDig
version: '${version}'
main: cn.marvelpixel.AreaDig
api-version: '1.16'
authors: [EmptySet]
description: 区域挖掘
website: marvelpixel.cn
commands:
  mplad:
    description: "z"
    permission: marvelpixel.main
depend:
  - MarvelPixel